services:
  plausible_db:
    image: postgres:16-alpine
    container_name: plausible_db
    restart: unless-stopped
    volumes:
      - /data/config_storage/plausible/db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 1m
    security_opt:
      - no-new-privileges:true  # helps to increase security
    networks:
      - intranet

  plausible_events_db:
    image: clickhouse/clickhouse-server:24.12-alpine
    container_name: plausible_events_db
    restart: unless-stopped
    volumes:
      - /data/config_storage/plausible/event-data:/var/lib/clickhouse
      - /data/config_storage/plausible/event-logs:/var/log/clickhouse-server
      - /data/config_storage/komodo/etc_komodo/repos/compose_main/plausable/logs.xml:/etc/clickhouse-server/config.d/logs.xml:ro
      # This makes ClickHouse bind to IPv4 only, since Docker doesn't enable IPv6 in bridge networks by default.
      # Fixes "Listen [::]:9000 failed: Address family for hostname not supported" warnings.
      - /data/config_storage/komodo/etc_komodo/repos/compose_main/plausable/ipv4-only.xml:/etc/clickhouse-server/config.d/ipv4-only.xml:ro
      # This makes ClickHouse consume less resources, which is useful for small setups.
      # https://clickhouse.com/docs/en/operations/tips#using-less-than-16gb-of-ram
      - /data/config_storage/komodo/etc_komodo/repos/compose_main/plausable/low-resources.xml:/etc/clickhouse-server/config.d/low-resources.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_SKIP_USER_SETUP=1
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 -O - http://127.0.0.1:8123/ping || exit 1"]
      start_period: 1m
    security_opt:
      - no-new-privileges:true  # helps to increase security
    networks:
      - intranet

  plausible:
    image: ghcr.io/plausible/community-edition:v3.1.0
    container_name: plausible
    restart: unless-stopped
    command: sh -c "/entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      plausible_db:
        condition: service_healthy
      plausible_events_db:
        condition: service_healthy
    volumes:
      - /data/config_data/plausible/plausible-data:/var/lib/plausible
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    environment:
      - TMPDIR=/var/lib/plausible/tmp
      # required: https://github.com/plausible/community-edition/wiki/configuration#required
      - BASE_URL=https://plausible.${DOMAIN}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      # optional: https://github.com/plausible/community-edition/wiki/configuration#optional
      # registration: https://github.com/plausible/community-edition/wiki/configuration#registration
      - TOTP_VAULT_KEY=${TOTP_VAULT_KEY}  # openssl rand -base64 32
      - DISABLE_REGISTRATION=true
      # web: https://github.com/plausible/community-edition/wiki/configuration#web
      - HTTP_PORT=8000
      # databases: https://github.com/plausible/community-edition/wiki/configuration#database
      - DATABASE_URL
      - CLICKHOUSE_DATABASE_URL
    security_opt:
      - no-new-privileges:true  # helps to increase security
    networks:
      - intranet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plausible.entrypoints=http"
      - "traefik.http.routers.plausible.rule=Host(`plausible.${DOMAIN}`)"
      - "traefik.http.middlewares.plausible-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.plausible.middlewares=plausible-https-redirect"
      - "traefik.http.routers.plausible-secure.entrypoints=https"
      - "traefik.http.routers.plausible-secure.rule=Host(`plausible.${DOMAIN}`)"
      - "traefik.http.routers.plausible-secure.tls=true"
      - "traefik.http.routers.plausible-secure.service=plausible"
      - "traefik.http.services.plausible.loadbalancer.server.port=8000"  # port of the service.
      - "traefik.docker.network=intranet"
      - "homepage.group=Other"
      - "homepage.name=plausible"
      - "homepage.icon=/images/plausible.png"
      - "homepage.href=https://plausible.${DOMAIN}/"

networks:
  intranet:
    external: true
