---
services:
  qbittorrent:
    image: quay.io/linuxserver.io/qbittorrent:5.1.4
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - TORRENTING_PORT=10866
      - WEBUI_PORT=8080
    volumes:
      - /data/config_storage/arr/qbittorrent:/config
      - /data/config_storage/arr/qbittorrent/complete:/complete
      - /data/mnt/torrents:/downloads/torrents
      - /data/mnt:/allMedia
      - /mnt/extra:/mnt
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true  # helps to increase security
    network_mode: container:gluetun
    labels:
      - "homepage.group=Media"
      - "homepage.name=qbittorrent"
      - "homepage.icon=/images/qbittorrent.png"
      - "homepage.href=https://qbittorrent.${DOMAIN}/"
