[[builder]]
name = "holmie"
[builder.config]
type = "Server"
params.server_id = "holmie"

##

[[builder]]
name = "holmgarage"
[builder.config]
type = "Server"
params.server_id = "holmgarage"

##

[[builder]]
name = "shady_desktop"
[builder.config]
type = "Server"
params.server_id = "shady_desktop"
