[[build]]
name = "build_skywatch"
description = "Goal: to get this to trigger on commits to skywatch.py"
[build.config]
builder = "holmie"
image_name = "skywatch"
files_on_host = true
build_path = "/etc/komodo/stacks/skywatch/skywatch"
image_registry = [
  { domain = "git.holmlab.org", account = "shady" }
]

##

[[build]]
name = "build_tidal-ui"
[build.config]
builder = "holmie"
image_name = "tidal-ui"
files_on_host = true
build_path = "/etc/komodo/repos/tidal-ui"
image_registry = [
  { domain = "git.holmlab.org", account = "shady" }
]
pre_build.path = "/etc/komodo/repos/tidal-ui"
pre_build.command = """
git pull
"""