[[stack]]
name = "beszelagent-holmgarage"
tags = ["holmgarage", "env", "criticality: 3"]
[stack.config]
server = "holmgarage"
project_name = "beszelagent-holmgarage"
linked_repo = "compose_main"
run_directory = "beszelagent"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/beszelagent-holmgarage.env"

##

[[stack]]
name = "immich-holmgarage"
tags = ["holmgarage", "env", "criticality: 2"]
[stack.config]
server = "holmgarage"
project_name = "immich-holmgarage"
linked_repo = "compose_main"
run_directory = "immich"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/immich.env"

##

[[stack]]
name = "pihole-holmgarage"
tags = ["holmgarage", "env", "criticality: 1"]
[stack.config]
server = "holmgarage"
project_name = "pihole-holmgarage"
linked_repo = "compose_main"
run_directory = "pihole"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/pihole.env"

##

[[stack]]
name = "traefik-holmgarage"
tags = ["holmgarage", "criticality: 1"]
[stack.config]
server = "holmgarage"
project_name = "traefik-holmgarage"
linked_repo = "compose_main"
run_directory = "traefik"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/traefik-holmgarage.env"

##

[[stack]]
name = "jellyfin-holmgarage"
tags = ["holmgarage", "criticality: 2"]
[stack.config]
server = "holmgarage"
project_name = "jellyfin-holmgarage"
linked_repo = "compose_main"
run_directory = "jellyfin"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/jellyfin-holmgarage.env"

##

[[stack]]
name = "mealie-holmgarage"
tags = ["holmgarage", "criticality: 5"]
[stack.config]
server = "holmgarage"
project_name = "mealie-holmgarage"
linked_repo = "compose_main"
run_directory = "mealie"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/mealie-holmgarage.env"

##

[[stack]]
name = "jellyseerr-holmgarage"
tags = ["holmgarage", "criticality: 4"]
[stack.config]
server = "holmgarage"
project_name = "jellyseerr-holmgarage"
linked_repo = "compose_main"
run_directory = "jellyseerr"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/jellyseerr-holmgarage.env"

##

[[stack]]
name = "filebrowser-holmgarage"
tags = ["holmgarage", "criticality: 5"]
[stack.config]
server = "holmgarage"
project_name = "filebrowser-holmgarage"
linked_repo = "compose_main"
run_directory = "filebrowser"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/filebrowser-holmgarage.env"

##

[[stack]]
name = "navidrome-holmgarage"
tags = ["holmgarage", "criticality: 4"]
[stack.config]
server = "holmgarage"
project_name = "navidrome-holmgarage"
linked_repo = "compose_main"
run_directory = "navidrome"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/navidrome-holmgarage.env"

##

[[stack]]
name = "homepage-holmgarage"
tags = ["holmgarage", "criticality: 2"]
[stack.config]
server = "holmgarage"
project_name = "homepage-holmgarage"
linked_repo = "compose_main"
run_directory = "homepage"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/homepage-holmgarage.env"

##

[[stack]]
name = "audiobookshelf-holmgarage"
tags = ["holmgarage", "criticality: 3"]
[stack.config]
server = "holmgarage"
project_name = "audiobookshelf-holmgarage"
linked_repo = "compose_main"
run_directory = "audiobookshelf"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/audiobookshelf-holmgarage.env"

##

[[stack]]
name = "dumbassets-holmgarage"
tags = ["holmgarage", "env", "criticality: 5"]
[stack.config]
server = "holmgarage"
project_name = "dumbassets-holmgarage"
linked_repo = "compose_main"
run_directory = "dumbassets"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/dumbassets.env"

##

[[stack]]
name = "homeassistant-holmgarage"
tags = ["holmgarage", "criticality: 1"]
[stack.config]
server = "holmgarage"
project_name = "homeassistant-holmgarage"
linked_repo = "compose_main"
run_directory = "homeassistant"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/homeassistant-holmgarage.env"

##

[[stack]]
name = "linkwarden-holmgarage"
tags = ["holmgarage", "env", "criticality: 5"]
[stack.config]
server = "holmgarage"
project_name = "linkwarden-holmgarage"
linked_repo = "compose_main"
run_directory = "linkwarden"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/linkwarden.env"

##

[[stack]]
name = "loggifly-holmgarage"
tags = ["holmgarage", "env", "criticality: 2"]
[stack.config]
server = "holmgarage"
project_name = "loggifly-holmgarage"
auto_pull = false
linked_repo = "compose_main"
run_directory = "loggifly"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/loggifly.env"

##

[[stack]]
name = "lubelogger-holmgarage"
tags = ["holmgarage", "criticality: 4"]
[stack.config]
server = "holmgarage"
project_name = "lubelogger-holmgarage"
linked_repo = "compose_main"
run_directory = "lubelogger"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/lubelogger-holmgarage.env"

##

[[stack]]
name = "nextcloud-holmgarage"
tags = ["holmgarage", "criticality: 3"]
[stack.config]
server = "holmgarage"
project_name = "nextcloud-holmgarage"
linked_repo = "compose_main"
run_directory = "nextcloud"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/nextcloud-holmgarage.env"

##

[[stack]]
name = "reactiveresume-holmgarage"
tags = ["holmgarage", "env", "criticality: 5"]
[stack.config]
server = "holmgarage"
project_name = "reactiveresume-holmgarage"
linked_repo = "compose_main"
run_directory = "reactiveresume"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/reactiveresume.env"

##

[[stack]]
name = "searxng-holmgarage"
tags = ["holmgarage", "criticality: 2"]
[stack.config]
server = "holmgarage"
project_name = "searxng-holmgarage"
linked_repo = "compose_main"
run_directory = "searxng"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/searxng-holmgarage.env"

##

[[stack]]
name = "speedtest-holmgarage"
tags = ["holmgarage", "criticality: 5"]
[stack.config]
server = "holmgarage"
project_name = "speedtest-holmgarage"
linked_repo = "compose_main"
run_directory = "speedtest"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/speedtest-holmgarage.env"

##

[[stack]]
name = "vaultwarden-holmgarage"
tags = ["holmgarage", "criticality: 2"]
[stack.config]
server = "holmgarage"
project_name = "vaultwarden-holmgarage"
linked_repo = "compose_main"
run_directory = "vaultwarden"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/vaultwarden-holmgarage.env"
##

[[stack]]
name = "plex-holmgarage"
tags = ["holmgarage", "criticality: 2"]
[stack.config]
server = "holmgarage"
project_name = "plex-holmgarage"
linked_repo = "compose_main"
run_directory = "plex"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/plex-holmgarage.env"

##

[[stack]]
name = "gluetun-holmgarage"
tags = ["holmgarage", "criticality: 2"]
[stack.config]
server = "holmgarage"
project_name = "gluetun-holmgarage"
linked_repo = "compose_main"
run_directory = "gluetun"
additional_env_files = [
  "/etc/komodo/domain.env",
  "/etc/komodo/qbit_port.env"
]
env_file_path = "/etc/komodo/env/gluetun-holmgarage.env"

##

[[stack]]
name = "qbittorrent-holmgarage"
tags = ["holmgarage", "criticality: 3"]
[stack.config]
server = "holmgarage"
project_name = "qbittorrent-holmgarage"
linked_repo = "compose_main"
run_directory = "qbittorrent"
additional_env_files = [
  "/etc/komodo/domain.env",
  "/etc/komodo/qbit_port.env"
]
env_file_path = "/etc/komodo/env/qbittorrent-holmgarage.env"

##

[[stack]]
name = "autobrr-holmgarage"
tags = ["holmgarage", "criticality: 5", "arr"]
[stack.config]
server = "holmgarage"
project_name = "autobrr-holmgarage"
linked_repo = "compose_main"
run_directory = "autobrr"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/autobrr-holmgarage.env"

##

[[stack]]
name = "jackett-holmgarage"
tags = ["holmgarage", "criticality: 4", "arr"]
[stack.config]
server = "holmgarage"
project_name = "jackett-holmgarage"
linked_repo = "compose_main"
run_directory = "jackett"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/jackett-holmgarage.env"

##

[[stack]]
name = "sonarr-holmgarage"
tags = ["holmgarage", "criticality: 4", "arr"]
[stack.config]
server = "holmgarage"
project_name = "sonarr-holmgarage"
linked_repo = "compose_main"
run_directory = "sonarr"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/sonarr-holmgarage.env"

##

[[stack]]
name = "radarr-holmgarage"
tags = ["holmgarage", "criticality: 4", "arr"]
[stack.config]
server = "holmgarage"
project_name = "radarr-holmgarage"
linked_repo = "compose_main"
run_directory = "radarr"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/radarr-holmgarage.env"

##

[[stack]]
name = "actualbudget-holmgarage"
tags = ["holmgarage", "criticality: 2"]
[stack.config]
server = "holmgarage"
project_name = "actualbudget-holmgarage"
linked_repo = "compose_main"
run_directory = "actualbudget"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/actualbudget-holmgarage.env"

##

[[stack]]
name = "bentopdf-holmgarage"
tags = ["holmgarage", "criticality: 5","ephemoral"]
[stack.config]
server = "holmgarage"
project_name = "bentopdf-holmgarage"
linked_repo = "compose_main"
run_directory = "bentopdf"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/bentopdf-holmgarage.env"
