[[stack]]
name = "filebrowser-mck"
tags = ["mck", "criticality: 5"]
[stack.config]
server = "mck"
project_name = "filebrowser-mck"
linked_repo = "compose_main"
run_directory = "filebrowser"

##

[[stack]]
name = "plex-mck"
tags = ["mck", "env", "criticality: 1"]
[stack.config]
server = "mck"
project_name = "plex-mck"
linked_repo = "compose_main"
run_directory = "plex"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/plex-mck.env"

##

[[stack]]
name = "beszelagent-mck"
tags = ["mck", "env", "criticality: 3"]
[stack.config]
server = "mck"
project_name = "beszelagent-mck"
linked_repo = "compose_main"
run_directory = "beszelagent"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/beszelagent-mck.env"

##

[[stack]]
name = "loggifly-mck"
tags = ["mck", "criticality: 1"]
[stack.config]
server = "mck"
project_name = "loggifly-mck"
linked_repo = "compose_main"
run_directory = "loggifly"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/loggifly-mck.env"

##

[[stack]]
name = "forgejo-mck"
tags = ["mck", "criticality: 1"]
[stack.config]
server = "mck"
project_name = "forgejo-mck"
linked_repo = "compose_main"
run_directory = "forgejo"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/forgejo-mck.env"

##

[[stack]]
name = "mck_hugo-mck"
tags = ["mck", "criticality: 1"]
[stack.config]
server = "mck"
links = [
  "http://100.117.173.46/",
  "http://192.168.1.24/"
]
project_name = "mck_hugo-mck"
linked_repo = "compose_main"
run_directory = "mck_hugo"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/mck_hugo-mck.env"

##

[[stack]]
name = "homeassistant-mck"
tags = ["mck", "criticality: 1"]
[stack.config]
server = "mck"
links = [
  "http://100.117.173.46:8123",
  "http://192.168.1.24:8123"
]
project_name = "homeassistant-mck"
linked_repo = "compose_main"
run_directory = "homeassistant"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/homeassistant-mck.env"

##

[[stack]]
name = "filegator-mck"
tags = ["mck", "criticality: 1"]
[stack.config]
server = "mck"
project_name = "filegator-mck"
linked_repo = "compose_main"
run_directory = "filegator"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/filegator-mck.env"
