[[repo]]
name = "compose_main"
[repo.config]
server = "holmie"
git_provider = "git.holmlab.org"
git_account = "komodo"
repo = "shady/compose"
branch = "main"

##

[[repo]]
name = "compose_test"
[repo.config]
server = "holmie"
git_provider = "git.holmlab.org"
git_account = "komodo"
repo = "shady/compose"
branch = "test"

##

[[repo]]
name = "tidal-ui"
[repo.config]
server = "holmie"
git_provider = "git.holmlab.org"
git_account = "komodo"
repo = "shady/tidal-ui"
branch = "main"

##

[[repo]]
name = "jetlag"
[repo.config]
server = "holmie"
git_provider = "git.holmlab.org"
git_account = "komodo"
repo = "shady/JetLagHideAndSeek"
branch = "main"