[[server]]
name = "holmie"
description = "The main server"
tags = ["holmie"]
[server.config]
address = "https://periphery.holmlab.org"
enabled = true
send_unreachable_alerts = false

##

[[server]]
name = "shady_desktop"
tags = ["shady_desktop"]
[server.config]
address = "https://periphery-shady.holmlab.org"
enabled = true
send_unreachable_alerts = false

##

[[server]]
name = "mck"
description = "192.168.1.24"
tags = ["mck", "MCC"]
[server.config]
tags = ["mck"]
address = "http://100.117.173.46:8120"
enabled = true
send_unreachable_alerts = true

##

[[server]]
name = "snow"
description = "192.168.x.x | snow.local | Optiplex 7040"
tags = ["snow"]
[server.config]
tags = ["snow"]
address = "http://100.71.57.32:8120"
enabled = true
send_unreachable_alerts = true

##

[[server]]
name = "holmgarage"
description = "192.168.0.46"
tags = ["holmgarage"]
[server.config]
tags = ["holmgarage"]
address = "http://100.91.217.107:8120"
enabled = true
send_unreachable_alerts = true

##

[[server]]
name = "turret"
description = "192.168.70.174"
tags = ["turret"]
[server.config]
tags = ["turret"]
address = "http://192.168.70.174:8120"
enabled = true
send_unreachable_alerts = false