[[stack]]
name = "crafty-shady"
tags = ["shady_desktop", "criticality: 2"]
[stack.config]
server = "shady_desktop"
project_name = "crafty"
linked_repo = "compose_main"
run_directory = "crafty"

##

[[stack]]
name = "immich-ml-shady"
tags = ["shady_desktop", "criticality: 3"]
[stack.config]
server = "shady_desktop"
project_name = "immich-ml"
linked_repo = "compose_main"
run_directory = "hosts/immich_remote_machine_learning"

##

[[stack]]
name = "beszelagent-shady"
tags = ["shady_desktop", "env", "criticality: 2"]
[stack.config]
server = "shady_desktop"
project_name = "beszelagent-shady"
linked_repo = "compose_main"
run_directory = "beszelagent"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/beszelagent-shady.env"

##

[[stack]]
name = "factorio-shady_desktop"
description = "192.168.50.16:34197 | 100.75.125.61:34197"
tags = ["shady_desktop", "criticality: 2"]
[stack.config]
server = "shady_desktop"
project_name = "factorio-shady_desktop"
linked_repo = "compose_main"
run_directory = "factorio"
additional_env_files = ["/etc/komodo/domain.env"]

##

[[stack]]
name = "foldingathome-shady_desktop"
tags = ["shady_desktop", "criticality: 1"]
[stack.config]
server = "shady_desktop"
links = [
  "https://v8-4.foldingathome.org/"
]
project_name = "foldingathome-shady_desktop"
linked_repo = "compose_main"
run_directory = "foldingathome"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/foldingathome-shady_desktop.env"

##

[[stack]]
name = "harborguard-shady_desktop"
tags = ["shady_desktop", "criticality: 1"]
[stack.config]
server = "shady_desktop"
project_name = "harborguard-shady_desktop"
linked_repo = "compose_main"
run_directory = "harborguard"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/harborguard-shady_desktop.env"

##

[[stack]]
name = "ollama-shady_desktop"
tags = ["shady_desktop", "criticality: 1"]
[stack.config]
server = "shady_desktop"
project_name = "ollama-shady_desktop"
linked_repo = "compose_main"
run_directory = "ollama"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/ollama-shady_desktop.env"
