##

[[stack]]
name = "beszelagent-snow"
tags = ["snow", "criticality: 1"]
[stack.config]
server = "snow"
project_name = "beszelagent-snow"
linked_repo = "compose_main"
run_directory = "beszelagent"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/beszelagent-snow.env"

##

[[stack]]
name = "immich-snow"
tags = ["snow", "criticality: 1"]
[stack.config]
server = "snow"
project_name = "immich-snow"
linked_repo = "compose_main"
run_directory = "immich"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/immich.env"

##

[[stack]]
name = "wireguard-snow"
tags = ["snow", "env", "criticality: 1"]
[stack.config]
server = "snow"
project_name = "wireguard"
linked_repo = "compose_main"
run_directory = "wireguard"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/wireguard.env"