##

[[stack]]
name = "beszelagent-snow"
tags = ["snow", "criticality: 1"]
[stack.config]
server = "snow"
project_name = "beszelagent-snow"
linked_repo = "compose_main"
run_directory = "beszelagent"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/beszelagent-snow.env"

##

[[stack]]
name = "immich-snow"
tags = ["snow", "criticality: 1"]
[stack.config]
server = "snow"
project_name = "immich-snow"
linked_repo = "compose_main"
run_directory = "immich"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/immich.env"

##

[[stack]]
name = "pihole-snow"
tags = ["snow", "criticality: 1"]
[stack.config]
server = "snow"
project_name = "pihole-snow"
linked_repo = "compose_main"
run_directory = "pihole"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/pihole-snow.env"

##

[[stack]]
name = "dnscrypt-proxy-snow"
tags = ["snow", "criticality: 1"]
[stack.config]
server = "snow"
project_name = "dnscrypt-proxy-snow"
linked_repo = "compose_main"
run_directory = "dnscrypt-proxy"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/dnscrypt-proxy-snow.env"

##

[[stack]]
name = "wireguard-snow"
tags = ["snow", "criticality: 1"]
[stack.config]
server = "snow"
project_name = "wireguard-snow"
linked_repo = "compose_main"
run_directory = "wireguard"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/wireguard-snow.env"
