[[resource_sync]]
name = "syncs"
tags = ["syncs"]
[resource_sync.config]
linked_repo = "compose_main"
resource_path = ["syncs/syncs.toml"]

##

[[resource_sync]]
name = "servers"
tags = ["servers"]
[resource_sync.config]
git_provider = "git.holmlab.org"
repo = "shady/compose"
git_account = "komodo"
resource_path = ["syncs/servers.toml"]

##

[[resource_sync]]
name = "repo"
tags = ["repo"]
[resource_sync.config]
git_provider = "git.holmlab.org"
repo = "shady/compose"
git_account = "komodo"
resource_path = ["syncs/repo.toml"]

##

[[resource_sync]]
name = "holmie"
tags = ["holmie"]
[resource_sync.config]
git_provider = "git.holmlab.org"
repo = "shady/compose"
git_account = "komodo"
resource_path = ["syncs/holmie.toml"]

##

[[resource_sync]]
name = "mck"
tags = ["mck"]
[resource_sync.config]
linked_repo = "compose_main"
resource_path = ["syncs/mck.toml"]

##

[[resource_sync]]
name = "shady_desktop"
tags = ["shady_desktop"]
[resource_sync.config]
git_provider = "git.holmlab.org"
repo = "shady/compose"
git_account = "komodo"
resource_path = ["syncs/shady_desktop.toml"]

##

[[resource_sync]]
name = "alert"
tags = ["alert"]
[resource_sync.config]
git_provider = "git.holmlab.org"
repo = "shady/compose"
git_account = "komodo"
resource_path = ["syncs/alert.toml"]

##

[[resource_sync]]
name = "procedure"
tags = ["procedure"]
[resource_sync.config]
git_provider = "git.holmlab.org"
repo = "shady/compose"
git_account = "komodo"
resource_path = ["syncs/procedure.toml"]

##

[[resource_sync]]
name = "builders"
tags = ["builders"]
[resource_sync.config]
git_provider = "git.holmlab.org"
repo = "shady/compose"
git_account = "komodo"
resource_path = ["syncs/builders.toml"]

##

[[resource_sync]]
name = "builds"
tags = ["builds"]
[resource_sync.config]
git_provider = "git.holmlab.org"
repo = "shady/compose"
git_account = "komodo"
resource_path = ["syncs/builds.toml"]

##

[[resource_sync]]
name = "snow"
tags = ["snow"]
[resource_sync.config]
git_provider = "git.holmlab.org"
repo = "shady/compose"
git_account = "komodo"
resource_path = ["syncs/snow.toml"]

##

[[resource_sync]]
name = "holmgarage"
tags = ["holmgarage"]
[resource_sync.config]
git_provider = "git.holmlab.org"
repo = "shady/compose"
git_account = "komodo"
resource_path = ["syncs/holmgarage.toml"]

##

[[resource_sync]]
name = "actions"
tags = ["actions"]
[resource_sync.config]
git_provider = "git.holmlab.org"
repo = "shady/compose"
git_account = "komodo"
resource_path = ["syncs/actions.toml"]

##

[[resource_sync]]
name = "turret"
tags = ["turret"]
[resource_sync.config]
git_provider = "git.holmlab.org"
repo = "shady/compose"
git_account = "komodo"
resource_path = ["syncs/turret.toml"]