[[stack]]
name = "adsb"
tags = ["turret", "env", "criticality: 3", "ephemoral"]
[stack.config]
server = "turret"
project_name = "adsb"
linked_repo = "compose_main"
run_directory = "adsb"
additional_env_files = ["/etc/komodo/domain.env"]
env_file_path = "/etc/komodo/env/adsb.env"