server:
  port: 80
  sources:
    - path: "/srv/data"
      config:
        defaultEnabled: true

auth:
  adminUsername: admin
  methods:
    password:
      enabled: true
      minLength: 6

frontend:
  name: "My FileBrowser"