---
services:
  filegator:
    image: filegator/filegator:v7.13.3
    volumes:
      - /data/mnt/shows:/var/www/filegator/repository
      - /data/dont_backup/filegator/logs:/private/logs
    security_opt:
      - no-new-privileges:true  # helps to increase security
    user: 1000:1000
    ports:
      - 8080:8080
    networks:
      - intranet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.assets.entrypoints=http"
      - "traefik.http.routers.assets.rule=Host(`assets.${DOMAIN}`)"
      - "traefik.http.middlewares.assets-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.assets.middlewares=assets-https-redirect"
      - "traefik.http.routers.assets-secure.entrypoints=https"
      - "traefik.http.routers.assets-secure.rule=Host(`assets.${DOMAIN}`)"
      - "traefik.http.routers.assets-secure.tls=true"
      - "traefik.http.routers.assets-secure.service=assets"
      - "traefik.http.services.assets.loadbalancer.server.port=8080"  # port of the service.
      - "traefik.docker.network=intranet"
      - "homepage.group=Other"
      - "homepage.name=assets"
      - "homepage.icon=/images/assets.png"
      - "homepage.href=https://assets.${DOMAIN}/"

networks:
  intranet:
    external: true
