---
services:
  dnscrypt-proxy:
    image: klutchell/dnscrypt-proxy:2.1.14
    container_name: dnscrypt
    volumes:
      - /data/config_storage/dnscrypt:/logs
      - /data/config_storage/komodo/etc_komodo/repos/compose_main/dnscrypt-proxy/example-dnscrypt-proxy.toml:/config/dnscrypt-proxy.toml:ro
    ports:
      - '5053:5053/udp'
      - '5053:5053/tcp'
    security_opt:
      - no-new-privileges:true  # helps to increase security
    networks:
      - intranet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dnscrypt.entrypoints=http"
      - "traefik.http.routers.dnscrypt.rule=Host(`dnscrypt.${DOMAIN}`)"
      - "traefik.http.middlewares.dnscrypt-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.dnscrypt.middlewares=dnscrypt-https-redirect"
      - "traefik.http.routers.dnscrypt-secure.entrypoints=https"
      - "traefik.http.routers.dnscrypt-secure.rule=Host(`dnscrypt.${DOMAIN}`)"
      - "traefik.http.routers.dnscrypt-secure.tls=true"
      - "traefik.http.routers.dnscrypt-secure.service=dnscrypt"
      - "traefik.http.services.dnscrypt.loadbalancer.server.port=8080"  # port of the service.
      - "traefik.docker.network=intranet"
      - "homepage.group=Other"
      - "homepage.name=dnscrypt"
      - "homepage.icon=/images/dnscrypt.png"
      - "homepage.href=https://dnscrypt.${DOMAIN}/"

networks:
  intranet:
    external: true
