---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.9.0
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${DOMAIN}
    volumes:
      - /data/config_storage/homepage/config:/app/config:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /data/config_storage/icons:/app/public/images:ro
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true  # helps to increase security
    networks:
      - intranet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.entrypoints=http"
      - "traefik.http.routers.homepage.rule=Host(`${DOMAIN}`)"
      - "traefik.http.middlewares.homepage-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.homepage.middlewares=homepage-https-redirect"
      - "traefik.http.routers.homepage-secure.entrypoints=https"
      - "traefik.http.routers.homepage-secure.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.homepage-secure.tls=true"
      - "traefik.http.routers.homepage-secure.service=homepage"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"  # port of the service.
      - "traefik.docker.network=intranet"
      - "traefik.http.routers.homepage.middlewares=anubis@docker"

networks:
  intranet:
    external: true
