---
services:
  tidal-ui:
    image: git.holmlab.org/shady/tidal-ui:3.3.1
    container_name: tidal-ui
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - TITLE=dl
      - PORT=5000
    security_opt:
      - no-new-privileges:true  # helps to increase security
    network_mode: container:gluetun
    labels:
      - "homepage.group=Other"
      - "homepage.name=tidal-ui"
      - "homepage.icon=/images/tidal.png"
      - "homepage.href=https://tidal-ui.${DOMAIN}/"

networks:
  intranet:
    external: true
