---
services:
  jackett:
    image: quay.io/linuxserver.io/jackett:0.24.361
    container_name: jackett
    restart: unless-stopped
    volumes:
      - /data/config_storage/arr/jackett:/config
    security_opt:
      - no-new-privileges:true  # helps to increase security
    network_mode: container:gluetun
    labels:
      - "homepage.group=Other"
      - "homepage.name=jackett"
      - "homepage.icon=/images/jackett.png"
      - "homepage.href=https://jackett.${DOMAIN}/"
