---
services:
  unbound:
    image: klutchell/unbound:1.24.2
    volumes:
      # touch /data/config_storage/unbound/custom.conf.d && chown 101:102 /data/config_storage/unbound/custom.conf.d 
      - /data/config_storage/unbound:/etc/unbound/custom.conf.d
      - /data/dont_backup/unbound/logs:/logs
    ports:
      - '5335:53/udp'
      - '5335:53/tcp'
    container_name: unbound
