---
services:
  crafty:
    container_name: crafty_container
    image: registry.gitlab.com/crafty-controller/crafty-4:4.9.0
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    ports:
      - "8443:8443"  # HTTPS web u
#      - "8123:8123"  # DYNMAP
      - "19132:19132/udp"  # BEDROCK
      - "25500-25600:25500-25600"  # MC SERV PORT RANGE
    volumes:
      - /data/dont_backup/crafty/backups:/crafty/backups
      - /data/config_storage/crafty/logs:/crafty/logs
      - /data/config_storage/crafty/servers:/crafty/servers
      - /data/config_storage/crafty/config:/crafty/app/config
      - /data/config_storage/crafty/import:/crafty/import
    security_opt:
      - no-new-privileges:true  # helps to increase security
    networks:
      - intranet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.crafty.entrypoints=http"
      - "traefik.http.routers.crafty.rule=Host(`crafty.${DOMAIN}`)"
      - "traefik.http.middlewares.crafty-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.crafty.middlewares=crafty-https-redirect"
      - "traefik.http.routers.crafty-secure.entrypoints=https"
      - "traefik.http.routers.crafty-secure.rule=Host(`crafty.${DOMAIN}`)"
      - "traefik.http.routers.crafty-secure.tls=true"
      - "traefik.http.routers.crafty-secure.service=crafty"
      - "traefik.http.services.crafty.loadbalancer.server.port=8443"  # port of the service.
      - "traefik.docker.network=intranet"
      - "traefik.http.services.crafty.loadbalancer.server.scheme=https"  # tell traefik to connect to Crafty via https instead of http
      - "homepage.group=Other"
      - "homepage.name=Crafty-holmie"
      - "homepage.icon=/images/crafty-controller.png"
      - "homepage.href=https://crafty.${DOMAIN}/"
      - "traefik.http.routers.mcmap.entrypoints=http"
      - "traefik.http.routers.mcmap.rule=Host(`mcmap.${DOMAIN}`)"
      - "traefik.http.middlewares.mcmap-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.mcmap.middlewares=mcmap-https-redirect"
      - "traefik.http.routers.mcmap-secure.entrypoints=https"
      - "traefik.http.routers.mcmap-secure.rule=Host(`mcmap.${DOMAIN}`)"
      - "traefik.http.routers.mcmap-secure.tls=true"
      - "traefik.http.routers.mcmap-secure.service=mcmap"
      - "traefik.http.services.mcmap.loadbalancer.server.port=25566"  # port of the service.
      - "traefik.http.routers.plan.entrypoints=http"
      - "traefik.http.routers.plan.rule=Host(`plan.${DOMAIN}`)"
      - "traefik.http.middlewares.plan-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.plan.middlewares=plan-https-redirect"
      - "traefik.http.routers.plan-secure.entrypoints=https"
      - "traefik.http.routers.plan-secure.rule=Host(`plan.${DOMAIN}`)"
      - "traefik.http.routers.plan-secure.tls=true"
      - "traefik.http.routers.plan-secure.service=plan"
      - "traefik.http.services.plan.loadbalancer.server.port=25567"  # port of the service.

networks:
  intranet:
    external: true
