---
services:
  registry:
    image: goharbor/registry-photon:v2.14.0
    container_name: registry
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - /data/config_storage/harbor/registry:/storage:z
      - /data/config_storage/harbor/config/registry/:/etc/registry/:z
    networks:
      - harbor
  registryctl:
    image: goharbor/harbor-registryctl:v2.14.0
    container_name: registryctl
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - /data/config_storage/harbor/registry:/storage:z
      - /data/config_storage/harbor/config/registry/:/etc/registry/:z
      - /data/config_storage/harbor/config/registryctl/config.yml:/etc/registryctl/config.yml
      - /data/config_storage/harbor/config/shared/trust-certificates:/harbor_cust_cert
    networks:
      - harbor
  postgresql:
    image: goharbor/harbor-db:v2.14.0
    container_name: harbor-db
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    volumes:
      - /data/config_storage/harbor/database:/var/lib/postgresql/data:z
    networks:
      harbor:
    depends_on:
    shm_size: '1gb'
  core:
    image: goharbor/harbor-core:v2.14.0
    container_name: harbor-core
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
    volumes:
      - /data/config_storage/harbor/ca_download/:/etc/core/ca/:z
      - /data/config_storage/harbor/:/data/:z
      - /data/config_storage/harbor/config/core/certificates/:/etc/core/certificates/:z
      - /data/config_storage/harbor/config/core/app.conf:/etc/core/app.conf
      - /data/config_storage/harbor/secret/core/private_key.pem:/etc/core/private_key.pem
      - /data/config_storage/harbor/secret/keys/secretkey:/etc/core/key
      - /data/config_storage/harbor/config/shared/trust-certificates:/harbor_cust_cert
    networks:
      harbor:
    depends_on:
      - registry
      - postgresql
  portal:
    image: goharbor/harbor-portal:v2.14.0
    container_name: harbor-portal
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    volumes:
      - /data/config_storage/harbor/config/portal/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - harbor
  jobservice:
    image: goharbor/harbor-jobservice:v2.14.0
    container_name: harbor-jobservice
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - /data/config_storage/harbor/job_logs:/var/log/jobs:z
      - /data/config_storage/harbor/config/jobservice/config.yml:/etc/jobservice/config.yml
      - /data/config_storage/harbor/config/shared/trust-certificates:/harbor_cust_cert
    networks:
      - harbor
    depends_on:
      - core
  proxy:
    image: goharbor/nginx-photon:v2.14.0
    container_name: nginx
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    volumes:
      - /data/config_storage/harbor/config/nginx:/etc/nginx:z
      - /data/config_storage/harbor/config/shared/trust-certificates:/harbor_cust_cert
    networks:
      - harbor
    ports:
      - 8089:8080
    depends_on:
      - registry
      - core
      - portal
  trivy-adapter:
    container_name: trivy-adapter
    image: goharbor/trivy-adapter-photon:v2.14.0
    restart: always
    cap_drop:
      - ALL
    networks:
      - harbor
    volumes:
      - /data/config_storage/harbor/trivy-adapter/trivy:/home/scanner/.cache/trivy
      - /data/config_storage/harbor/trivy-adapter/reports:/home/scanner/.cache/reports
      - /data/config_storage/harbor/config/shared/trust-certificates:/harbor_cust_cert
networks:
  harbor:
    external: false
