---
services:
  prosody:
    image: prosodyim/prosody:13.0
    volumes:
      - /data/config_storage/prosody/modules:/usr/lib/prosody-modules
      - /data/dont_backup/prosody:/var/log/prosody
      - /data/config_storage/prosody/configuration:/etc/prosody
      - /data/config_storage/komodo/etc_komodo/repos/compose_main/prosody/prosody.cfg.lua:/etc/prosody/prosody.cfg.lua:ro
    environment:
      - PASSWORD=${PASSWORD}
      - DOMAIN=xmpp.${DOMAIN}
      - LOCAL=local
    ports:
      - "5222:5222"  # Client-to-server connections
      - "5269:5269"  # Server-to-server federation
      - "5280:5280"  # HTTP admin and BOSH
      - "5281:5281"  # HTTPS admin
    security_opt:
      - no-new-privileges:true  # helps to increase security
    networks:
      - intranet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.xmpp.entrypoints=http"
      - "traefik.http.routers.xmpp.rule=Host(`xmpp.${DOMAIN}`)"
      - "traefik.http.middlewares.xmpp-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.xmpp.middlewares=xmpp-https-redirect"
      - "traefik.http.routers.xmpp-secure.entrypoints=https"
      - "traefik.http.routers.xmpp-secure.rule=Host(`xmpp.${DOMAIN}`)"
      - "traefik.http.routers.xmpp-secure.tls=true"
      - "traefik.http.routers.xmpp-secure.service=xmpp"
      - "traefik.http.services.xmpp.loadbalancer.server.port=5281"  # port of the service.
      - "traefik.docker.network=intranet"
      - "homepage.group=Other"
      - "homepage.name=xmpp"
      - "homepage.icon=/images/prosody.png"
      - "homepage.href=https://xmpp.${DOMAIN}/"

networks:
  intranet:
    external: true
