---
services:
  frigate-notify:
    image: ghcr.io/0x2142/frigate-notify:v0.5.4
    environment:
      - TZ=America/New_York
    volumes:
      - /data/config_storage/frigate-notify/config.yml:/app/config.yml
    restart: unless-stopped
