---
services:
  frigate-notify:
    image: ghcr.io/0x2142/frigate-notify:v0.5.4
    environment:
      - TZ=America/New_York
      - FN_CONFIGFILE= "/app/config/config.yml"
    volumes:
      - /data/config_storage/frigate-notify/:/app/config/
    restart: unless-stopped
