---
services:
  postgres_mattermost:
    container_name: postgres_mattermost
    image: postgres:14-alpine
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    user: 2000:2000
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - /data/config_storage/mattermost/postgres:/var/lib/postgresql/data
    environment:
      - TZ=America/New_York
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=mattermost
    networks:
      - intranet

  mattermost:
    depends_on:
      - postgres_mattermost
    image: mattermost/mattermost-team-edition:11.4.1
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: false
    user: 2000:2000
    tmpfs:
      - /tmp
    volumes:
      - /data/config_storage/mattermost/config:/mattermost/config:rw
      - /data/config_storage/mattermost/data:/mattermost/data:rw
      - /data/config_storage/mattermost/logs:/mattermost/logs:rw
      - /data/config_storage/mattermost/plugins:/mattermost/plugins:rw
      - /data/config_storage/mattermost/client_plugins:/mattermost/client/plugins:rw
      - /data/config_storage/mattermost/bleve_indexes:/mattermost/bleve-indexes:rw
    ports:
      - "8065:8065"
    environment:
      - TZ=America/New_York
      - APP_PORT=8065
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:${POSTGRES_PASSWORD}@postgres_mattermost:5432/mattermost?sslmode=disable&connect_timeout=10
      - MM_BLEVESETTINGS_INDEXDIR=/mattermost/bleve-indexes
      - MM_SERVICESETTINGS_SITEURL=https://mattermost.${DOMAIN}/
    networks:
      - intranet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mattermost.entrypoints=http"
      - "traefik.http.routers.mattermost.rule=Host(`mattermost.${DOMAIN}`)"
      - "traefik.http.middlewares.mattermost-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.mattermost.middlewares=mattermost-https-redirect"
      - "traefik.http.routers.mattermost-secure.entrypoints=https"
      - "traefik.http.routers.mattermost-secure.rule=Host(`mattermost.${DOMAIN}`)"
      - "traefik.http.routers.mattermost-secure.tls=true"
      - "traefik.http.routers.mattermost-secure.service=mattermost"
      - "traefik.http.services.mattermost.loadbalancer.server.port=8065"  # port of the service.
      - "traefik.docker.network=intranet"
      - "homepage.group=Other"
      - "homepage.name=mattermost"
      - "homepage.icon=/images/mattermost.png"
      - "homepage.href=https://mattermost.${DOMAIN}/"

networks:
  intranet:
    external: true
