---
services:
  frigate:
    container_name: frigate
    privileged: true  # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s  # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:0.16.4
    shm_size: "512mb"  # update for your cameras based on calculation above
    devices:
#      - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
#      - /dev/apex_0:/dev/apex_0  # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
#      - /dev/video11:/dev/video11  # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128  # For intel hwaccel, needs to be updated for your hardware
      - /dev/video0:/dev/video0  # usb webcam
    group_add:
      - "44"  # video GID (getent group video | cut -d: -f3)
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/config_storage/frigate:/config
      #- /data/config_storage/komodo/etc_komodo/repos/compose_main/frigate/config.yaml:/config/config.yaml:ro
      - /data/mnt/frigate:/media/frigate
      - type: tmpfs  # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
#      - "8971:8971"  # web ui
      # - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554"  # RTSP feeds
      - "8555:8555/tcp"  # WebRTC over tcp
      - "8555:8555/udp"  # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: ${FRIGATE_RTSP_PASSWORD}
    security_opt:
      - no-new-privileges:true  # helps to increase security
    networks:
      - intranet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frigate.entrypoints=http"
      - "traefik.http.routers.frigate.rule=Host(`frigate.${DOMAIN}`)"
      - "traefik.http.middlewares.frigate-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.frigate.middlewares=frigate-https-redirect"
      - "traefik.http.routers.frigate-secure.entrypoints=https"
      - "traefik.http.routers.frigate-secure.rule=Host(`frigate.${DOMAIN}`)"
      - "traefik.http.routers.frigate-secure.tls=true"
      - "traefik.http.routers.frigate-secure.service=frigate"
      - "traefik.http.services.frigate.loadbalancer.server.port=8971"  # port of the service.
      - "traefik.http.services.frigate.loadbalancer.server.scheme=https"  # tell traefik to connect to frigate via https instead of http
      - "traefik.docker.network=intranet"
      - "homepage.group=Other"
      - "homepage.name=frigate"
      - "homepage.icon=/images/frigate.png"
      - "homepage.href=https://frigate.${DOMAIN}/"

networks:
  intranet:
    external: true
