---
mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

cameras:
  usb_webcam:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: /dev/video0
          # V4L2â€‘specific arguments
          input_args: "-f v4l2 -framerate 30 -video_size 1280x720"
          # you can add `-thread_queue_size 512` if you see frame drops
          roles:
            - record


tls:
  enabled: false
