---
mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

cameras:
  usb_webcam:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: /dev/video0
          # minimal V4L2 args â€“ no fps filter
          input_args: "-f v4l2 -framerate 30 -video_size 1280x720 -pixel_format yuyv -thread_queue_size 512"
          roles:
            - record


tls:
  enabled: false
