---
mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi
  path: "/usr/bin/ffmpeg"

cameras:
  usb_webcam:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: /dev/video0
          input_args: preset-rtsp-restream
          roles:
            - record

tls:
  enabled: false
