---
mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

cameras:
  usb_webcam:
    ffmpeg:
      hwaccel_args: " "
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: /dev/video0
          input_args: "-f v4l2 -framerate 30 -video_size 1280x720"
          roles:
            - record

tls:
  enabled: false
