---
mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

cameras:
  usb_webcam:
    ffmpeg:
      hwaccel_args: ' '
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: /dev/video0
          input_args: -f v4l2 -framerate 30 -video_size 1920x1080
          roles:
            - record
  520a:
    ffmpeg:
      inputs:
        - path: rtsp://viewer:Password@192.168.50.232:554
          roles:
            - record

tls:
  enabled: false
detect:
  enabled: false
version: 0.16-0
