---
services:
  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:v1.73.0
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    volumes:
      - /data/config_storage/autobrr/config:/config
    security_opt:
      - no-new-privileges:true  # helps to increase security
    networks:
      - intranet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.autobrr.entrypoints=http"
      - "traefik.http.routers.autobrr.rule=Host(`autobrr.${DOMAIN}`)"
      - "traefik.http.middlewares.autobrr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.autobrr.middlewares=autobrr-https-redirect"
      - "traefik.http.routers.autobrr-secure.entrypoints=https"
      - "traefik.http.routers.autobrr-secure.rule=Host(`autobrr.${DOMAIN}`)"
      - "traefik.http.routers.autobrr-secure.tls=true"
      - "traefik.http.routers.autobrr-secure.service=autobrr"
      - "traefik.http.services.autobrr.loadbalancer.server.port=7474"  # port of the service.
      - "traefik.docker.network=intranet"
      - "homepage.group=Other"
      - "homepage.name=autobrr"
      - "homepage.icon=/images/autobrr.png"
      - "homepage.href=https://autobrr.${DOMAIN}/"

networks:
  intranet:
    external: true
