---
services:
  mautrix:
    image: dock.mau.dev/mautrix/discord:v0.7.4  # https://mau.dev/mautrix/discord/container_registry/53
    container_name: mautrix_discord_synapse
    restart: unless-stopped
    volumes:
      - /data/config_storage/mautrix_discord_synapse:/data:z
