---
services:
  qui:
    image: ghcr.io/autobrr/qui:v1.10.0
    container_name: qui
    restart: unless-stopped
    ports:
      - "7476:7476"
    volumes:
      - /data/config_storage/qui:/config
    environment:
      QUI__HOST: "0.0.0.0"
    security_opt:
      - no-new-privileges:true  # helps to increase security
    networks:
      - intranet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qui.entrypoints=http"
      - "traefik.http.routers.qui.rule=Host(`qui.${DOMAIN}`)"
      - "traefik.http.middlewares.qui-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.qui.middlewares=qui-https-redirect"
      - "traefik.http.routers.qui-secure.entrypoints=https"
      - "traefik.http.routers.qui-secure.rule=Host(`qui.${DOMAIN}`)"
      - "traefik.http.routers.qui-secure.tls=true"
      - "traefik.http.routers.qui-secure.service=qui"
      - "traefik.http.services.qui.loadbalancer.server.port=7476"  # port of the service.
      - "traefik.docker.network=intranet"
      - "homepage.group=Media"
      - "homepage.name=qui"
      - "homepage.icon=/images/autobrr.png"
      - "homepage.href=https://qui.${DOMAIN}/"

networks:
  intranet:
    external: true
