---
services:
  music-assistant-server:
    image: ghcr.io/music-assistant/server:2.7.1
    container_name: music-assistant-server
    restart: unless-stopped
    # host is required to for device discovery (https://www.music-assistant.io/installation/ see "host network mode")
    network_mode: host
    volumes:
      - /data/config_storage/music-assistant:/data
      - /data/music:/music:ro
      - /data/audiobooks:/audiobooks:ro
      - /data/podcasts:/podcasts:ro
    environment:
      - LOG_LEVEL=info
    security_opt:
      - no-new-privileges:true  # helps to increase security
#    networks:
#      - intranet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.music-assistant.entrypoints=http"
      - "traefik.http.routers.music-assistant.rule=Host(`music-assistant.${DOMAIN}`)"
      - "traefik.http.middlewares.music-assistant-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.music-assistant.middlewares=music-assistant-https-redirect"
      - "traefik.http.routers.music-assistant-secure.entrypoints=https"
      - "traefik.http.routers.music-assistant-secure.rule=Host(`music-assistant.${DOMAIN}`)"
      - "traefik.http.routers.music-assistant-secure.tls=true"
      - "traefik.http.routers.music-assistant-secure.service=music-assistant"
      - "traefik.http.services.music-assistant.loadbalancer.server.port=8095"  # port of the service.
      - "traefik.docker.network=intranet"
      - "homepage.group=Media"
      - "homepage.name=music-assistant"
      - "homepage.icon=/images/music-assistant.png"
      - "homepage.href=http://192.168.50.65:8095/#/home"

#networks:
#  intranet:
#    external: true
