---
services:
  docker-in-docker:
    image: docker:29.1.2-dind-rootless
    container_name: 'docker-in-docker'
    privileged: 'true'
    command: ['dockerd', '-H', 'tcp://0.0.0.0:2375', '--tls=false']
    restart: 'unless-stopped'

  runner:
    image: 'data.forgejo.org/forgejo/runner:12.5.0'
    links:
      - docker-in-docker
    depends_on:
      docker-in-docker:
        condition: service_started
    container_name: 'runner'
    environment:
      DOCKER_HOST: tcp://docker-in-docker:2375
    user: 1000:1000
    volumes:
      - /data/dont_backup/forgejo/data:/data  # see commands for setting up this dir: https://forgejo.org/docs/next/admin/actions/runner-installation/#oci-image-installation
    restart: 'unless-stopped'
    command: '/bin/sh -c "sleep 5; forgejo-runner daemon"'  # for normal use; post registration

    # command: '/bin/sh -c "while : ; do sleep 1 ; done ;"'  # FOR REGISTRATION - see just above https://forgejo.org/docs/next/admin/actions/runner-installation/#standard-registration
